package pe.com.nttdata.SeleniumCucumber;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class HerokuTestChrome {
  private static WebDriver driver;
  private static Map<String, Object> vars;
  private static JavascriptExecutor js;
  @BeforeAll
  public static void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterAll
  public static void tearDown() {
    driver.quit();
  }
  //@Test
  public void altaCliente() {
    driver.get("https://christophermen4.herokuapp.com/");
    //driver.manage().window().setSize(new Dimension(1536, 1400));
    driver.manage().window().maximize();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Agregar")).click();
    driver.findElement(By.id("nombre")).click();
    driver.findElement(By.id("nombre")).sendKeys("carlos");
    driver.findElement(By.id("apellido")).click();
    driver.findElement(By.id("apellido")).sendKeys("garcia");
    driver.findElement(By.id("direccion")).click();
    driver.findElement(By.id("direccion")).sendKeys("mz");
    driver.findElement(By.id("telefono")).click();
    driver.findElement(By.id("telefono")).sendKeys("999999999");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("correo@hotmail.com");
    driver.findElement(By.id("pension")).click();
    driver.findElement(By.id("pension")).sendKeys(Keys.BACK_SPACE);
    driver.findElement(By.id("pension")).sendKeys(Keys.BACK_SPACE);
    driver.findElement(By.id("pension")).sendKeys(Keys.BACK_SPACE);
    driver.findElement(By.id("pension")).sendKeys("3000");
    driver.findElement(By.id("fechaNacimiento")).click();
    driver.findElement(By.id("fechaNacimiento")).sendKeys("03111982");
    js.executeScript("window.scrollBy(0,2000)");
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
    driver.findElement(By.id("pais")).click();
    {
      WebElement dropdown = driver.findElement(By.id("pais"));
      dropdown.findElement(By.xpath("//option[. = 'Peru']")).click();
    }
    driver.findElement(By.id("tipoSeguro")).click();
    {
      WebElement dropdown = driver.findElement(By.id("tipoSeguro"));
      dropdown.findElement(By.xpath("//option[. = 'Rimac']")).click();
    }

    driver.findElement(By.cssSelector(".btn")).click();

    String text = driver.findElement(By.xpath("//div[contains(@class,'alert alert-success alert-dismissable fade show')]/strong")).getText();
    System.out.println("El valor es: " + text);
    //validar una prueba unitaria
    Assertions.assertEquals(text, "Cliente guardado con éxito!");
  }

  //@Test
  public void eliminarCliente() {
    driver.get("https://christophermen4.herokuapp.com/");
    driver.manage().window().maximize();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.cssSelector(".col-12:nth-child(2)")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
    driver.findElement(By.cssSelector("tr:nth-child(3) .btn-danger")).click();

    String text = driver.findElement(By.xpath("//div[contains(@class,'alert alert-warning alert-dismissable fade show')]/strong")).getText();
    System.out.println("El valor es: " + text);
    Assertions.assertEquals(text, "Cliente eliminado con éxito!"); //validar respuestas de una prueba unitaria
  }

  @Test
  public void modificarCliente() throws InterruptedException {
    driver.get("https://christophermen4.herokuapp.com/");
    driver.manage().window().maximize();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("Editar")).click();

    js.executeScript("window.scrollBy(0,2000)");
    Thread.sleep(2000);

    driver.findElement(By.id("pais")).click();
    {
      WebElement dropdown = driver.findElement(By.id("pais"));
      dropdown.findElement(By.xpath("//option[. = 'Brasil']")).click();
    }
    driver.findElement(By.id("tipoSeguro")).click();
    {
      WebElement dropdown = driver.findElement(By.id("tipoSeguro"));
      dropdown.findElement(By.xpath("//option[. = 'La Positiva']")).click();
    }
    driver.findElement(By.cssSelector(".btn")).click();

    String text = driver.findElement(By.xpath("//div[contains(@class,'alert alert-success alert-dismissable fade show')]/strong")).getText();
    System.out.println("El valor es: " + text);
    Assertions.assertEquals(text, "Cliente guardado con éxito!");
  }
}
